name: nwash_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


# dependencies:
#   flutter:
#     sdk: flutter
#   permission_handler: ^11.4.0
#   image_picker: 1.1.2 
#   flutter_sound: 9.25.3 # Updated to the latest version
#   geolocator: 13.0.2
#   path_provider: 2.1.5 
#   camera: 0.11.1 
#   location: 8.0.0 
#   sqflite: ^2.0.0+4
#   logging: 1.3.0 
#   intl: ^0.20.2
#   google_mlkit_speech: ^0.2.0
#   shared_preferences: 2.5.3
  
  

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.4.0
  image_picker: ^1.1.2 
  flutter_sound: ^9.25.3
  geolocator: ^13.0.2
  path_provider: ^2.1.5 
  camera: ^0.11.1 
  location: ^8.0.0 
  sqflite: ^2.0.0+4
  logging: ^1.3.0 
  intl: ^0.20.2
  google_ml_kit: 0.20.0 
  shared_preferences: ^2.5.3
  speech_to_text: 7.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
   # Add your image assets here if you have any
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: assets/fonts/MyCustomFont-Regular.ttf  # Ensure this file exists